"""
Story 10.4: live codegen integration coverage for database view definitions.

These tests run the actual `spacetime generate` flow in isolated temp
directories so the generated Story 10.4 fixture is anchored to the real CLI
behavior instead of inferred strings alone.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
VIEW_MODULE = ROOT / "spacetime" / "modules" / "view_test"
SMOKE_MODULE = ROOT / "spacetime" / "modules" / "smoke_test"
POST_PROCESSOR = ROOT / "scripts" / "codegen" / "detect-godot-types.py"


def _require_tool(name: str) -> str:
    path = shutil.which(name)
    if path is None:
        pytest.skip(f"{name} not available on PATH")
    return path


def _run_codegen(module_root: Path, namespace: str, output_dir: Path, cargo_target_dir: Path) -> None:
    spacetime = _require_tool("spacetime")
    python3 = _require_tool("python3")
    env = os.environ.copy()
    env["CARGO_NET_OFFLINE"] = "true"
    env["CARGO_TARGET_DIR"] = str(cargo_target_dir)

    generate = subprocess.run(
        [
            spacetime,
            "generate",
            "--lang",
            "csharp",
            "--namespace",
            namespace,
            "--out-dir",
            str(output_dir),
            "--module-path",
            str(module_root),
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        timeout=300,
        env=env,
        check=False,
    )
    assert generate.returncode == 0, (
        "spacetime generate must succeed for Story 10.4 integration coverage.\n"
        f"stdout:\n{generate.stdout}\n"
        f"stderr:\n{generate.stderr}"
    )

    post = subprocess.run(
        [python3, str(POST_PROCESSOR), str(output_dir / "Types")],
        cwd=ROOT,
        capture_output=True,
        text=True,
        timeout=120,
        env=env,
        check=False,
    )
    assert post.returncode == 0, (
        "detect-godot-types.py must succeed after view-definition codegen.\n"
        f"stdout:\n{post.stdout}\n"
        f"stderr:\n{post.stderr}"
    )


@pytest.fixture(scope="session")
def story_10_4_codegen_outputs(tmp_path_factory: pytest.TempPathFactory) -> dict[str, Path]:
    workspace = tmp_path_factory.mktemp("story-10-4-view-codegen")
    view_output = workspace / "view_output"
    smoke_output = workspace / "smoke_output"
    _run_codegen(
        module_root=VIEW_MODULE,
        namespace="SpacetimeDB.ViewTestIntegration",
        output_dir=view_output,
        cargo_target_dir=workspace / "cargo-view-target",
    )
    _run_codegen(
        module_root=SMOKE_MODULE,
        namespace="SpacetimeDB.SmokeNoViewIntegration",
        output_dir=smoke_output,
        cargo_target_dir=workspace / "cargo-smoke-target",
    )
    return {
        "workspace": workspace,
        "view_output": view_output,
        "smoke_output": smoke_output,
    }


def test_view_codegen_integration_produces_expected_view_artifacts(
    story_10_4_codegen_outputs: dict[str, Path],
) -> None:
    view_output = story_10_4_codegen_outputs["view_output"]
    required = [
        view_output / "SpacetimeDBClient.g.cs",
        view_output / "Tables" / "Player.g.cs",
        view_output / "Tables" / "PlayerOne.g.cs",
        view_output / "Tables" / "PlayersForLevelTwo.g.cs",
        view_output / "Types" / "Player.g.cs",
        view_output / "Types" / "LevelTwoPlayerSummary.g.cs",
        view_output / "Reducers" / "SeedPlayers.g.cs",
    ]
    for path in required:
        assert path.is_file(), f"{path} must be generated by the real Story 10.4 codegen workflow."


def test_view_codegen_integration_emits_typed_view_subscription_surface(
    story_10_4_codegen_outputs: dict[str, Path],
) -> None:
    client = (story_10_4_codegen_outputs["view_output"] / "SpacetimeDBClient.g.cs").read_text(
        encoding="utf-8"
    )
    for expected in (
        "AddTable(PlayerOne = new(conn))",
        "AddTable(PlayersForLevelTwo = new(conn))",
        'new QueryBuilder().From.PlayerOne().ToSql()',
        'new QueryBuilder().From.PlayersForLevelTwo().ToSql()',
        'public global::SpacetimeDB.Table<Player, PlayerOneCols, PlayerOneIxCols> PlayerOne()',
        'public global::SpacetimeDB.Table<LevelTwoPlayerSummary, PlayersForLevelTwoCols, PlayersForLevelTwoIxCols> PlayersForLevelTwo()',
    ):
        assert expected in client, (
            "The real CLI-generated Story 10.4 bindings must expose view definitions "
            f"through the typed subscription/query surface. Missing {expected!r}."
        )


def test_codegen_without_view_exports_remains_table_only(
    story_10_4_codegen_outputs: dict[str, Path],
) -> None:
    smoke_output = story_10_4_codegen_outputs["smoke_output"]
    smoke_client = (smoke_output / "SpacetimeDBClient.g.cs").read_text(encoding="utf-8")
    for unexpected in ("PlayerOne", "PlayersForLevelTwo", "player_one", "players_for_level_two"):
        assert unexpected not in smoke_client, (
            "A module without view definitions must not generate Story 10.4 view surfaces."
        )
    assert not (smoke_output / "Tables" / "PlayerOne.g.cs").exists(), (
        "Non-view modules must not emit PlayerOne.g.cs."
    )
    assert not (smoke_output / "Tables" / "PlayersForLevelTwo.g.cs").exists(), (
        "Non-view modules must not emit PlayersForLevelTwo.g.cs."
    )


def test_view_codegen_integration_harness_avoids_hardcoded_sleeps() -> None:
    source = Path(__file__).read_text(encoding="utf-8")
    sanitized = source.replace('"time.sleep("', "")
    assert "time.sleep(" not in sanitized, (
        "Story 10.4 codegen integration coverage must rely on subprocess timeouts, not hardcoded sleeps."
    )
