# THIS FILE IS AUTOMATICALLY GENERATED BY godot-spacetime GDScript codegen.
# EDITS TO THIS FILE WILL NOT BE SAVED. Regenerate with: bash scripts/codegen/generate-gdscript-smoke-test.sh
extends RefCounted

const BsatnReaderScript = preload("res://addons/godot_spacetime/src/Internal/Platform/GDScript/bsatn_reader.gd")

var _rows: Array = []
var _row_script = null

var count: int:
	get:
		return _rows.size()

func _init() -> void:
	_row_script = _load_generated_script("../Types/smoke_test.gd")

func _load_generated_script(relative_path: String):
	var base_dir: String = get_script().resource_path.get_base_dir()
	return load(base_dir.path_join(relative_path))

func sql_table_name() -> String:
	return "smoke_test"

func cache_table_name() -> String:
	return "SmokeTest"

func decode_row(row_bytes: PackedByteArray):
	var reader = BsatnReaderScript.new(row_bytes)
	var row = _row_script.new()
	row.read_from_bsatn(reader)
	return row

func get_primary_key(row) -> Variant:
	return row.id

func iter() -> Array:
	return _rows.duplicate(true)

func replace_rows(rows: Array) -> void:
	_rows = rows.duplicate(true)
