# THIS FILE IS AUTOMATICALLY GENERATED BY godot-spacetime GDScript codegen.
# EDITS TO THIS FILE WILL NOT BE SAVED. Regenerate with: bash scripts/codegen/generate-gdscript-smoke-test.sh
extends Resource

var x: float = 0.0
var y: float = 0.0
var z: float = 0.0
var w: float = 0.0

func read_from_bsatn(reader) -> void:
	x = reader.read_f32()
	y = reader.read_f32()
	z = reader.read_f32()
	w = reader.read_f32()

func write_to_bsatn(writer) -> void:
	writer.write_f32(x)
	writer.write_f32(y)
	writer.write_f32(z)
	writer.write_f32(w)

func to_dictionary() -> Dictionary:
	return {
		"x": x,
		"y": y,
		"z": z,
		"w": w,
	}

func to_godot_value() -> Quaternion:
	return Quaternion(x, y, z, w)
