# THIS FILE IS AUTOMATICALLY GENERATED BY godot-spacetime GDScript codegen.
# EDITS TO THIS FILE WILL NOT BE SAVED. Regenerate with: bash scripts/codegen/generate-gdscript-smoke-test.sh
extends Resource

var r: float = 0.0
var g: float = 0.0
var b: float = 0.0
var a: float = 0.0

func read_from_bsatn(reader) -> void:
	r = reader.read_f32()
	g = reader.read_f32()
	b = reader.read_f32()
	a = reader.read_f32()

func write_to_bsatn(writer) -> void:
	writer.write_f32(r)
	writer.write_f32(g)
	writer.write_f32(b)
	writer.write_f32(a)

func to_dictionary() -> Dictionary:
	return {
		"r": r,
		"g": g,
		"b": b,
		"a": a,
	}

func to_godot_value() -> Color:
	return Color(r, g, b, a)
