# THIS FILE IS AUTOMATICALLY GENERATED BY godot-spacetime GDScript codegen.
# EDITS TO THIS FILE WILL NOT BE SAVED. Regenerate with: bash scripts/codegen/generate-gdscript-smoke-test.sh
extends Resource

var id: int = 0
var value: String = ""

func read_from_bsatn(reader) -> void:
	id = reader.read_u32()
	value = reader.read_string()

func write_to_bsatn(writer) -> void:
	writer.write_u32(id)
	writer.write_string(value)

func to_dictionary() -> Dictionary:
	return {
		"id": id,
		"value": value,
	}
