# THIS FILE IS AUTOMATICALLY GENERATED BY godot-spacetime GDScript codegen.
# EDITS TO THIS FILE WILL NOT BE SAVED. Regenerate with: bash scripts/codegen/generate-gdscript-smoke-test.sh
extends Resource

var id: int = 0
var position: Vector2 = Vector2.ZERO
var orientation: Quaternion = Quaternion.IDENTITY
var color: Color = Color(0.0, 0.0, 0.0, 1.0)
var tile: Vector3i = Vector3i.ZERO

func read_from_bsatn(reader) -> void:
	id = reader.read_u32()
	position = reader.read_vector2()
	orientation = reader.read_quaternion()
	color = reader.read_color()
	tile = reader.read_vector3i()

func write_to_bsatn(writer) -> void:
	writer.write_u32(id)
	writer.write_vector2(position)
	writer.write_quaternion(orientation)
	writer.write_color(color)
	writer.write_vector3i(tile)

func to_dictionary() -> Dictionary:
	return {
		"id": id,
		"position": position,
		"orientation": orientation,
		"color": color,
		"tile": tile,
	}
