# THIS FILE IS AUTOMATICALLY GENERATED BY godot-spacetime GDScript codegen.
# EDITS TO THIS FILE WILL NOT BE SAVED. Regenerate with: bash scripts/codegen/generate-gdscript-smoke-test.sh
extends Resource

var x: float = 0.0
var y: float = 0.0

func read_from_bsatn(reader) -> void:
	x = reader.read_f32()
	y = reader.read_f32()

func write_to_bsatn(writer) -> void:
	writer.write_f32(x)
	writer.write_f32(y)

func to_dictionary() -> Dictionary:
	return {
		"x": x,
		"y": y,
	}

func to_godot_value() -> Vector2:
	return Vector2(x, y)
