# THIS FILE IS AUTOMATICALLY GENERATED BY godot-spacetime GDScript codegen.
# EDITS TO THIS FILE WILL NOT BE SAVED. Regenerate with: bash scripts/codegen/generate-gdscript-smoke-test.sh
extends Resource

var x: int = 0
var y: int = 0
var z: int = 0

func read_from_bsatn(reader) -> void:
	x = reader.read_i32()
	y = reader.read_i32()
	z = reader.read_i32()

func write_to_bsatn(writer) -> void:
	writer.write_i32(x)
	writer.write_i32(y)
	writer.write_i32(z)

func to_dictionary() -> Dictionary:
	return {
		"x": x,
		"y": y,
		"z": z,
	}

func to_godot_value() -> Vector3i:
	return Vector3i(x, y, z)
