# THIS FILE IS AUTOMATICALLY GENERATED BY godot-spacetime GDScript codegen.
# EDITS TO THIS FILE WILL NOT BE SAVED. Regenerate with: bash scripts/codegen/generate-gdscript-smoke-test.sh
extends RefCounted

var SmokeTest = null
var TypedEntity = null

func _load_generated_script(relative_path: String):
	var base_dir: String = get_script().resource_path.get_base_dir()
	return load(base_dir.path_join(relative_path))

func _init() -> void:
	SmokeTest = _load_generated_script("Tables/smoke_test_table.gd").new()
	TypedEntity = _load_generated_script("Tables/typed_entity_table.gd").new()

func get_table_contracts() -> Array:
	return [SmokeTest, TypedEntity]
