# THIS FILE IS AUTOMATICALLY GENERATED BY godot-spacetime GDScript codegen.
# EDITS TO THIS FILE WILL NOT BE SAVED. Regenerate with: bash scripts/codegen/generate-gdscript-smoke-test.sh
extends RefCounted

const BsatnWriterScript = preload("res://addons/godot_spacetime/src/Internal/Platform/GDScript/bsatn_writer.gd")

var _connection_service = null

func _init(connection_service = null) -> void:
	_connection_service = connection_service

func attach_connection(connection_service) -> void:
	_connection_service = connection_service

func _invoke(reducer_name: String, args_bytes: PackedByteArray) -> String:
	if _connection_service == null:
		push_error("Generated reducers require a GdscriptConnectionService. Pass one to spacetimedb_client.gd or call attach_connection().")
		return ""
	return _connection_service.invoke_reducer(reducer_name, args_bytes)

func ping() -> String:
	return _invoke("ping", PackedByteArray())

func ping_insert(value: String) -> String:
	var writer = BsatnWriterScript.new()
	writer.write_string(value)
	return _invoke("ping_insert", writer.get_bytes())
