#!/usr/bin/env python3
"""
generate-gdscript-bindings.py

Repo-owned GDScript emitter for SpacetimeDB modules.

This script intentionally treats the official C# bindings as the stable schema
front-end for Story 11.5. It does not assume upstream `spacetime generate
--lang gdscript` support exists.
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType

BANNER_TEMPLATE = (
    "# THIS FILE IS AUTOMATICALLY GENERATED BY godot-spacetime GDScript codegen.\n"
    "# EDITS TO THIS FILE WILL NOT BE SAVED. Regenerate with: {regen_command}\n"
    "\n"
)

DATA_MEMBER_RE = re.compile(r'\[DataMember\(Name = "([^"]+)"\)\]')
PUBLIC_FIELD_RE = re.compile(r"^\s*public\s+([A-Za-z_][\w<>\[\],.?]*)\s+(\w+)\s*;")
TABLE_REMOTE_NAME_RE = re.compile(r'protected override string RemoteTableName => "([^"]+)";')
TABLE_HANDLE_RE = re.compile(
    r"public sealed class (\w+)Handle : RemoteTableHandle<EventContext, (\w+)>"
)
TABLE_PRIMARY_KEY_RE = re.compile(r"GetPrimaryKey\(\w+ row\) => row\.(\w+);")
CLIENT_ADD_TABLE_RE = re.compile(r"AddTable\((\w+) = new\(conn\)\);")
REDUCER_METHOD_RE = re.compile(r"^\s*public void (\w+)\(([^)]*)\)", re.MULTILINE)
REDUCER_NAME_RE = re.compile(r'string IReducerArgs.ReducerName => "([^"]+)";')
CSHARP_VERSION_RE = re.compile(r"generated using spacetimedb cli version ([^ ]+)", re.IGNORECASE)

PRIMITIVE_CODECS: dict[str, tuple[str, str, str]] = {
    "bool": ("bool", "false", "reader.read_bool()"),
    "byte": ("int", "0", "reader.read_u8()"),
    "sbyte": ("int", "0", "reader.read_i8()"),
    "ushort": ("int", "0", "reader.read_u16()"),
    "short": ("int", "0", "reader.read_i16()"),
    "uint": ("int", "0", "reader.read_u32()"),
    "int": ("int", "0", "reader.read_i32()"),
    "ulong": ("int", "0", "reader.read_u64()"),
    "long": ("int", "0", "reader.read_i64()"),
    "float": ("float", "0.0", "reader.read_f32()"),
    "double": ("float", "0.0", "reader.read_f64()"),
    "string": ("String", '""', "reader.read_string()"),
    "byte[]": ("PackedByteArray", "PackedByteArray()", "reader.read_bytes()"),
}

PRIMITIVE_WRITERS: dict[str, str] = {
    "bool": "writer.write_bool({value})",
    "byte": "writer.write_u8({value})",
    "sbyte": "writer.write_i8({value})",
    "ushort": "writer.write_u16({value})",
    "short": "writer.write_i16({value})",
    "uint": "writer.write_u32({value})",
    "int": "writer.write_i32({value})",
    "ulong": "writer.write_u64({value})",
    "long": "writer.write_i64({value})",
    "float": "writer.write_f32({value})",
    "double": "writer.write_f64({value})",
    "string": "writer.write_string({value})",
    "byte[]": "writer.write_bytes({value})",
}

GODOT_LAYOUTS: dict[str, tuple[str, str, str, str]] = {
    "Vector2": ("Vector2", "Vector2.ZERO", "reader.read_vector2()", "writer.write_vector2({value})"),
    "Vector3": ("Vector3", "Vector3.ZERO", "reader.read_vector3()", "writer.write_vector3({value})"),
    "Vector4": ("Vector4", "Vector4.ZERO", "reader.read_vector4()", "writer.write_vector4({value})"),
    "Quaternion": ("Quaternion", "Quaternion.IDENTITY", "reader.read_quaternion()", "writer.write_quaternion({value})"),
    "Color": ("Color", "Color(0.0, 0.0, 0.0, 1.0)", "reader.read_color()", "writer.write_color({value})"),
    "Vector2I": ("Vector2i", "Vector2i.ZERO", "reader.read_vector2i()", "writer.write_vector2i({value})"),
    "Vector3I": ("Vector3i", "Vector3i.ZERO", "reader.read_vector3i()", "writer.write_vector3i({value})"),
    "Vector4I": ("Vector4i", "Vector4i.ZERO", "reader.read_vector4i()", "writer.write_vector4i({value})"),
}


@dataclass(frozen=True)
class FieldSpec:
    name: str
    csharp_name: str
    csharp_type: str
    type_kind: str
    gdscript_type: str
    default_value: str
    read_expression: str
    write_expression: str
    helper_path: str = ""


@dataclass(frozen=True)
class TypeSpec:
    name: str
    file_stem: str
    fields: tuple[FieldSpec, ...]
    godot_layout: str | None


@dataclass(frozen=True)
class TableSpec:
    sql_name: str
    cache_name: str
    row_type_name: str
    file_stem: str
    primary_key_field: str


@dataclass(frozen=True)
class ReducerSpec:
    reducer_name: str
    method_name: str
    args: tuple[FieldSpec, ...]


@dataclass(frozen=True)
class Context:
    module_name: str
    regen_command: str
    cli_version: str
    types: tuple[TypeSpec, ...]
    types_by_name: dict[str, TypeSpec]
    tables: tuple[TableSpec, ...]
    reducers: tuple[ReducerSpec, ...]


def _snake_case(name: str) -> str:
    value = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    value = re.sub(r"([a-z])([A-Z])", r"\1_\2", value)
    return value.lower()


def _load_detect_module(repo_root: Path) -> ModuleType:
    script_path = repo_root / "scripts" / "codegen" / "detect-godot-types.py"
    spec = importlib.util.spec_from_file_location("detect_godot_types", script_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load {script_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _parse_data_member_fields(source: str) -> tuple[tuple[str, str, str], ...]:
    pending_name: str | None = None
    fields: list[tuple[str, str, str]] = []
    for line in source.splitlines():
        data_member = DATA_MEMBER_RE.search(line)
        if data_member:
            pending_name = data_member.group(1)
            continue
        if pending_name is None:
            continue
        field_match = PUBLIC_FIELD_RE.match(line)
        if field_match is None:
            continue
        csharp_type, csharp_name = field_match.groups()
        fields.append((pending_name, csharp_name, csharp_type))
        pending_name = None
    return tuple(fields)


def _parse_types(csharp_bindings_dir: Path, detect_module: ModuleType) -> tuple[TypeSpec, ...]:
    types_dir = csharp_bindings_dir / "Types"
    if not types_dir.is_dir():
        raise RuntimeError(f"Missing Types/ directory under {csharp_bindings_dir}")

    raw_specs: list[tuple[str, str, tuple[tuple[str, str, str], ...], str | None]] = []
    for path in sorted(types_dir.glob("*.g.cs")):
        if path.name.endswith(".godot.g.cs"):
            continue
        source = path.read_text(encoding="utf-8")
        parsed = detect_module.parse_class(source, source_name=str(path))
        if parsed is None:
            continue
        class_name, parsed_fields = parsed
        data_member_fields = _parse_data_member_fields(source)
        layout = detect_module.detect_layout(class_name, parsed_fields)
        if len(data_member_fields) != len(parsed_fields):
            raise RuntimeError(
                f"{path} parsed {len(parsed_fields)} field(s) via detect-godot-types.py "
                f"but only {len(data_member_fields)} DataMember field(s) for GDScript emission"
            )

        raw_specs.append((class_name, _snake_case(class_name), data_member_fields, layout))

    specs_by_name = {
        class_name: TypeSpec(name=class_name, file_stem=file_stem, fields=(), godot_layout=layout)
        for class_name, file_stem, _fields, layout in raw_specs
    }
    resolved_specs: list[TypeSpec] = []
    for class_name, file_stem, data_member_fields, layout in raw_specs:
        layout_lookup = {name: value.godot_layout for name, value in specs_by_name.items()}
        sorted_type_names = tuple(sorted(specs_by_name))
        resolved_fields = tuple(
            _build_field_spec(
                field_name=field_name,
                csharp_name=csharp_name,
                csharp_type=csharp_type,
                types_dir_name="Types",
                types_by_name=sorted_type_names,
                godot_layout_lookup=layout_lookup,
            )
            for field_name, csharp_name, csharp_type in data_member_fields
        )
        resolved_specs.append(
            TypeSpec(
                name=class_name,
                file_stem=file_stem,
                fields=resolved_fields,
                godot_layout=layout,
            )
        )
    return tuple(sorted(resolved_specs, key=lambda spec: spec.file_stem))


def _parse_tables(csharp_bindings_dir: Path, ordered_cache_names: tuple[str, ...]) -> tuple[TableSpec, ...]:
    tables_dir = csharp_bindings_dir / "Tables"
    if not tables_dir.is_dir():
        raise RuntimeError(f"Missing Tables/ directory under {csharp_bindings_dir}")

    specs_by_cache_name: dict[str, TableSpec] = {}
    for path in sorted(tables_dir.glob("*.g.cs")):
        source = path.read_text(encoding="utf-8")
        handle_match = TABLE_HANDLE_RE.search(source)
        remote_match = TABLE_REMOTE_NAME_RE.search(source)
        primary_key_match = TABLE_PRIMARY_KEY_RE.search(source)
        if handle_match is None or remote_match is None or primary_key_match is None:
            raise RuntimeError(f"Unable to parse Story 11.5 table metadata from {path}")
        cache_name = handle_match.group(2)
        specs_by_cache_name[cache_name] = TableSpec(
            sql_name=remote_match.group(1),
            cache_name=cache_name,
            row_type_name=cache_name,
            file_stem=_snake_case(cache_name),
            primary_key_field=_snake_case(primary_key_match.group(1)),
        )

    ordered_tables: list[TableSpec] = []
    for cache_name in ordered_cache_names:
        if cache_name not in specs_by_cache_name:
            raise RuntimeError(
                f"SpacetimeDBClient.g.cs references table {cache_name}, but no matching Tables/*.g.cs metadata was found"
            )
        ordered_tables.append(specs_by_cache_name[cache_name])
    return tuple(ordered_tables)


def _parse_table_order(csharp_bindings_dir: Path) -> tuple[str, ...]:
    client_path = csharp_bindings_dir / "SpacetimeDBClient.g.cs"
    source = client_path.read_text(encoding="utf-8")
    ordered = tuple(CLIENT_ADD_TABLE_RE.findall(source))
    if not ordered:
        raise RuntimeError(f"Unable to parse RemoteTables registration order from {client_path}")
    return ordered


def _parse_cli_version(csharp_bindings_dir: Path) -> str:
    client_source = (csharp_bindings_dir / "SpacetimeDBClient.g.cs").read_text(encoding="utf-8")
    match = CSHARP_VERSION_RE.search(client_source)
    return match.group(1) if match else "unknown"


def _parse_reducers(
    csharp_bindings_dir: Path,
    types_by_name: dict[str, TypeSpec],
) -> tuple[ReducerSpec, ...]:
    reducers_dir = csharp_bindings_dir / "Reducers"
    if not reducers_dir.is_dir():
        return ()

    layout_lookup = {name: spec.godot_layout for name, spec in types_by_name.items()}
    specs: list[ReducerSpec] = []
    for path in sorted(reducers_dir.glob("*.g.cs")):
        source = path.read_text(encoding="utf-8")
        method_match = REDUCER_METHOD_RE.search(source)
        reducer_name_match = REDUCER_NAME_RE.search(source)
        if method_match is None or reducer_name_match is None:
            raise RuntimeError(f"Unable to parse Story 11.5 reducer metadata from {path}")

        args: list[FieldSpec] = []
        params = method_match.group(2).strip()
        if params:
            for raw_param in params.split(","):
                csharp_type, param_name = raw_param.strip().rsplit(" ", maxsplit=1)
                args.append(
                    _build_field_spec(
                        field_name=param_name,
                        csharp_name=param_name[:1].upper() + param_name[1:],
                        csharp_type=csharp_type,
                        types_dir_name="Types",
                        types_by_name=tuple(sorted(types_by_name)),
                        godot_layout_lookup=layout_lookup,
                    )
                )

        specs.append(
            ReducerSpec(
                reducer_name=reducer_name_match.group(1),
                method_name=_snake_case(method_match.group(1)),
                args=tuple(args),
            )
        )
    return tuple(sorted(specs, key=lambda spec: spec.reducer_name))


def _build_field_spec(
    *,
    field_name: str,
    csharp_name: str,
    csharp_type: str,
    types_dir_name: str,
    types_by_name: tuple[str, ...],
    godot_layout_lookup: dict[str, str | None],
) -> FieldSpec:
    if csharp_type in PRIMITIVE_CODECS:
        gdscript_type, default_value, read_expression = PRIMITIVE_CODECS[csharp_type]
        return FieldSpec(
            name=field_name,
            csharp_name=csharp_name,
            csharp_type=csharp_type,
            type_kind="primitive",
            gdscript_type=gdscript_type,
            default_value=default_value,
            read_expression=read_expression,
            write_expression=PRIMITIVE_WRITERS[csharp_type].format(value=field_name),
        )

    layout = godot_layout_lookup.get(csharp_type)
    if layout is not None:
        gdscript_type, default_value, read_expression, write_template = GODOT_LAYOUTS[layout]
        return FieldSpec(
            name=field_name,
            csharp_name=csharp_name,
            csharp_type=csharp_type,
            type_kind="godot-layout",
            gdscript_type=gdscript_type,
            default_value=default_value,
            read_expression=read_expression,
            write_expression=write_template.format(value=field_name),
            helper_path=f"{types_dir_name}/{_snake_case(csharp_type)}.gd",
        )

    if csharp_type in types_by_name:
        helper_path = f"{types_dir_name}/{_snake_case(csharp_type)}.gd"
        return FieldSpec(
            name=field_name,
            csharp_name=csharp_name,
            csharp_type=csharp_type,
            type_kind="generated-type",
            gdscript_type="Variant",
            default_value="null",
            read_expression=(
                "_read_generated_value(%s, reader)" % _quote_gd(helper_path)
            ),
            write_expression=(
                "_write_generated_value(%s, writer, %s)" % (_quote_gd(helper_path), field_name)
            ),
            helper_path=helper_path,
        )

    raise RuntimeError(f"Unsupported Story 11.5 field type: {csharp_type}")


def _quote_gd(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _render_type_script(spec: TypeSpec, regen_command: str) -> str:
    lines: list[str] = [BANNER_TEMPLATE.format(regen_command=regen_command).rstrip(), "extends Resource", ""]

    if any(field.type_kind == "generated-type" for field in spec.fields):
        lines.extend(_generated_type_helpers())

    for field in spec.fields:
        lines.append(f"var {field.name}: {field.gdscript_type} = {field.default_value}")
    if spec.fields:
        lines.append("")
    lines.extend(
        [
            "func read_from_bsatn(reader) -> void:",
        ]
    )
    if spec.fields:
        for field in spec.fields:
            lines.append(f"\t{field.name} = {field.read_expression}")
    else:
        lines.append("\tpass")
    lines.extend(["", "func write_to_bsatn(writer) -> void:"])
    if spec.fields:
        for field in spec.fields:
            lines.append(f"\t{field.write_expression}")
    else:
        lines.append("\tpass")
    lines.extend(["", "func to_dictionary() -> Dictionary:"])
    if spec.fields:
        lines.append("\treturn {")
        for field in spec.fields:
            lines.append(f'\t\t"{field.name}": {field.name},')
        lines.append("\t}")
    else:
        lines.append("\treturn {}")

    if spec.godot_layout is not None:
        gdscript_type, _, _, _ = GODOT_LAYOUTS[spec.godot_layout]
        constructor_args = ", ".join(field.name for field in spec.fields)
        lines.extend(
            [
                "",
                f"func to_godot_value() -> {gdscript_type}:",
                f"\treturn {gdscript_type}({constructor_args})",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def _generated_type_helpers() -> list[str]:
    return [
        "func _load_generated_script(relative_path: String):",
        "\tvar base_dir := get_script().resource_path.get_base_dir()",
        "\treturn load(base_dir.path_join(relative_path))",
        "",
        "func _read_generated_value(relative_path: String, reader):",
        "\tvar script = _load_generated_script(relative_path)",
        "\tvar value = script.new()",
        "\tvalue.read_from_bsatn(reader)",
        "\treturn value",
        "",
        "func _write_generated_value(relative_path: String, writer, value) -> void:",
        "\tif value == null:",
        '\t\tpush_error("Generated GDScript binding received a null nested value for %s." % relative_path)',
        "\t\treturn",
        "\tif value.has_method(\"write_to_bsatn\"):",
        "\t\tvalue.write_to_bsatn(writer)",
        "\t\treturn",
        '\tpush_error("Generated GDScript binding could not serialize nested value for %s." % relative_path)',
        "",
    ]


def _render_table_script(table: TableSpec, row_spec: TypeSpec, regen_command: str) -> str:
    row_relative_path = f"../Types/{row_spec.file_stem}.gd"
    return "\n".join(
        [
            BANNER_TEMPLATE.format(regen_command=regen_command).rstrip(),
            "extends RefCounted",
            "",
            'const BsatnReaderScript = preload("res://addons/godot_spacetime/src/Internal/Platform/GDScript/bsatn_reader.gd")',
            "",
            "var _rows: Array = []",
            "var _row_script = null",
            "",
            "var count: int:",
            "\tget:",
            "\t\treturn _rows.size()",
            "",
            "func _init() -> void:",
            f"\t_row_script = _load_generated_script({_quote_gd(row_relative_path)})",
            "",
            "func _load_generated_script(relative_path: String):",
            "\tvar base_dir := get_script().resource_path.get_base_dir()",
            "\treturn load(base_dir.path_join(relative_path))",
            "",
            "func sql_table_name() -> String:",
            f'\treturn "{table.sql_name}"',
            "",
            "func cache_table_name() -> String:",
            f'\treturn "{table.cache_name}"',
            "",
            "func decode_row(row_bytes: PackedByteArray):",
            "\tvar reader = BsatnReaderScript.new(row_bytes)",
            "\tvar row = _row_script.new()",
            "\trow.read_from_bsatn(reader)",
            "\treturn row",
            "",
            "func get_primary_key(row) -> Variant:",
            f"\treturn row.{table.primary_key_field}",
            "",
            "func iter() -> Array:",
            "\treturn _rows.duplicate(true)",
            "",
            "func replace_rows(rows: Array) -> void:",
            "\t_rows = rows.duplicate(true)",
            "",
        ]
    )


def _render_remote_tables(tables: tuple[TableSpec, ...], regen_command: str) -> str:
    lines = [
        BANNER_TEMPLATE.format(regen_command=regen_command).rstrip(),
        "extends RefCounted",
        "",
    ]
    for table in tables:
        lines.append(f"var {table.cache_name} = null")
    lines.extend(
        [
            "",
            "func _load_generated_script(relative_path: String):",
            "\tvar base_dir := get_script().resource_path.get_base_dir()",
            "\treturn load(base_dir.path_join(relative_path))",
            "",
            "func _init() -> void:",
        ]
    )
    for table in tables:
        lines.append(
            f"\t{table.cache_name} = _load_generated_script({_quote_gd(f'Tables/{table.file_stem}_table.gd')}).new()"
        )
    lines.extend(["", "func get_table_contracts() -> Array:", "\treturn [" + ", ".join(table.cache_name for table in tables) + "]", ""])
    return "\n".join(lines)


def _render_remote_reducers(reducers: tuple[ReducerSpec, ...], regen_command: str) -> str:
    lines = [
        BANNER_TEMPLATE.format(regen_command=regen_command).rstrip(),
        "extends RefCounted",
        "",
        'const BsatnWriterScript = preload("res://addons/godot_spacetime/src/Internal/Platform/GDScript/bsatn_writer.gd")',
        "",
        "var _connection_service = null",
        "",
        "func _init(connection_service = null) -> void:",
        "\t_connection_service = connection_service",
        "",
        "func attach_connection(connection_service) -> void:",
        "\t_connection_service = connection_service",
        "",
        "func _invoke(reducer_name: String, args_bytes: PackedByteArray) -> String:",
        "\tif _connection_service == null:",
        '\t\tpush_error("Generated reducers require a GdscriptConnectionService. Pass one to spacetimedb_client.gd or call attach_connection().")',
        '\t\treturn ""',
        "\treturn _connection_service.invoke_reducer(reducer_name, args_bytes)",
    ]
    for reducer in reducers:
        lines.extend(["", f"func {reducer.method_name}({ _render_arg_signature(reducer.args) }) -> String:"])
        if reducer.args:
            lines.append("\tvar writer = BsatnWriterScript.new()")
            for arg in reducer.args:
                lines.append(f"\t{arg.write_expression}")
            lines.append(
                f"\treturn _invoke({_quote_gd(reducer.reducer_name)}, writer.get_bytes())"
            )
        else:
            lines.append(
                f"\treturn _invoke({_quote_gd(reducer.reducer_name)}, PackedByteArray())"
            )
    lines.append("")
    return "\n".join(lines)


def _render_arg_signature(args: tuple[FieldSpec, ...]) -> str:
    if not args:
        return ""
    return ", ".join(f"{arg.name}: {arg.gdscript_type}" for arg in args)


def _render_spacetimedb_client(tables: tuple[TableSpec, ...], regen_command: str) -> str:
    lines = [
        BANNER_TEMPLATE.format(regen_command=regen_command).rstrip(),
        "extends RefCounted",
        "",
        "var tables = null",
        "var reducers = null",
    ]
    for table in tables:
        lines.append(f"var {table.cache_name} = null")
    lines.extend(
        [
            "",
            "func _load_generated_script(relative_path: String):",
            "\tvar base_dir := get_script().resource_path.get_base_dir()",
            "\treturn load(base_dir.path_join(relative_path))",
            "",
            "func _init(connection_service = null) -> void:",
            '\ttables = _load_generated_script("remote_tables.gd").new()',
            '\treducers = _load_generated_script("remote_reducers.gd").new(connection_service)',
        ]
    )
    for table in tables:
        lines.append(f"\t{table.cache_name} = tables.{table.cache_name}")
    lines.extend(
        [
            "",
            "func attach_connection(connection_service) -> void:",
            "\treducers.attach_connection(connection_service)",
            "",
            "func get_table_contracts() -> Array:",
            "\treturn tables.get_table_contracts()",
            "",
        ]
    )
    return "\n".join(lines)


def _render_readme(context: Context) -> str:
    return (
        f"# Generated GDScript Bindings — `{context.module_name}` module\n\n"
        f"These files are generated by `{context.regen_command}` and committed as read-only artifacts.\n\n"
        f"The pinned upstream CLI does not directly emit GDScript bindings, so the repo first generates authoritative C# bindings and then runs `scripts/codegen/generate-gdscript-bindings.py` to emit this GDScript surface.\n\n"
        f"Output directory: `tests/fixtures/gdscript_generated/{context.module_name}/`\n\n"
        "Do not edit these files manually.\n"
    )


def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _build_context(args: argparse.Namespace) -> Context:
    csharp_bindings_dir = args.csharp_bindings_dir.resolve()
    repo_root = Path(__file__).resolve().parents[2]
    detect_module = _load_detect_module(repo_root)
    types = _parse_types(csharp_bindings_dir, detect_module)
    types_by_name = {spec.name: spec for spec in types}
    table_order = _parse_table_order(csharp_bindings_dir)
    tables = _parse_tables(csharp_bindings_dir, table_order)
    reducers = _parse_reducers(csharp_bindings_dir, types_by_name)
    return Context(
        module_name=args.module_name,
        regen_command=args.regen_command,
        cli_version=_parse_cli_version(csharp_bindings_dir),
        types=types,
        types_by_name=types_by_name,
        tables=tables,
        reducers=reducers,
    )


def _validate_args(args: argparse.Namespace) -> None:
    if not args.csharp_bindings_dir.is_dir():
        raise RuntimeError(f"--csharp-bindings-dir must be an existing directory: {args.csharp_bindings_dir}")
    if args.out_dir.resolve() == args.csharp_bindings_dir.resolve():
        raise RuntimeError("--out-dir must differ from --csharp-bindings-dir")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Emit repo-owned GDScript bindings from existing generated C# bindings."
    )
    parser.add_argument("--csharp-bindings-dir", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--module-name", required=True)
    parser.add_argument("--regen-command", required=True)
    args = parser.parse_args()

    _validate_args(args)
    context = _build_context(args)

    out_dir = args.out_dir.resolve()
    if out_dir.exists():
        shutil.rmtree(out_dir)
    (out_dir / "Tables").mkdir(parents=True, exist_ok=True)
    (out_dir / "Types").mkdir(parents=True, exist_ok=True)

    _write_text(out_dir / "README.md", _render_readme(context))
    for type_spec in context.types:
        _write_text(
            out_dir / "Types" / f"{type_spec.file_stem}.gd",
            _render_type_script(type_spec, context.regen_command),
        )
    for table_spec in context.tables:
        row_spec = context.types_by_name[table_spec.row_type_name]
        _write_text(
            out_dir / "Tables" / f"{table_spec.file_stem}_table.gd",
            _render_table_script(table_spec, row_spec, context.regen_command),
        )
    _write_text(out_dir / "remote_tables.gd", _render_remote_tables(context.tables, context.regen_command))
    _write_text(out_dir / "remote_reducers.gd", _render_remote_reducers(context.reducers, context.regen_command))
    _write_text(out_dir / "spacetimedb_client.gd", _render_spacetimedb_client(context.tables, context.regen_command))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
