#!/usr/bin/env bash
# generate-smoke-test.sh
#
# Generates C# client bindings from the smoke_test SpacetimeDB module.
# Output is committed to demo/generated/smoke_test/ as read-only artifacts.
#
# Usage (run from repo root):
#   bash scripts/codegen/generate-smoke-test.sh
#
# Prerequisites:
#   - spacetime CLI installed (SpacetimeDB 2.1+)
#   - Run from the repository root

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT_DIR="${REPO_ROOT}/demo/generated/smoke_test"
MODULE_PATH="${REPO_ROOT}/spacetime/modules/smoke_test"
LOCKFILE_PATH="${MODULE_PATH}/Cargo.lock"
CARGO_TARGET_DIR="$(mktemp -d "${TMPDIR:-/tmp}/godot-spacetime-smoke-test-target.XXXXXX")"

cleanup() {
  rm -rf "${CARGO_TARGET_DIR}"
  rm -f "${LOCKFILE_PATH}"
}

write_generated_readme() {
  cat > "${OUTPUT_DIR}/README.md" <<'EOF'
# Generated Bindings — smoke_test module

These files are generated by `scripts/codegen/generate-smoke-test.sh` and committed as read-only artifacts.

**Do not edit these files manually.** To refresh after a schema change, run:

```bash
bash scripts/codegen/generate-smoke-test.sh
```

Generated with: `spacetime generate --lang csharp`
Source module: `spacetime/modules/smoke_test/`
EOF
}

trap cleanup EXIT

echo "Clearing previous output: ${OUTPUT_DIR}"
rm -rf "${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}"

echo "Running spacetime generate..."
CARGO_TARGET_DIR="${CARGO_TARGET_DIR}" spacetime generate \
  --lang csharp \
  --out-dir "${OUTPUT_DIR}" \
  --module-path "${MODULE_PATH}"

write_generated_readme

echo "Generated bindings written to: ${OUTPUT_DIR}"
ls -1 "${OUTPUT_DIR}"
